# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Fri Jun 30 23:06:05 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(385, 275)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.source_box = QtGui.QLineEdit(Form)
        self.source_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.source_box.setObjectName("source_box")
        self.horizontalLayout.addWidget(self.source_box)
        self.source_button = QtGui.QPushButton(Form)
        self.source_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.source_button.setObjectName("source_button")
        self.horizontalLayout.addWidget(self.source_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.target_box = QtGui.QLineEdit(Form)
        self.target_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.target_box.setObjectName("target_box")
        self.horizontalLayout_2.addWidget(self.target_box)
        self.target_button = QtGui.QPushButton(Form)
        self.target_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.target_button.setObjectName("target_button")
        self.horizontalLayout_2.addWidget(self.target_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.select_box = QtGui.QComboBox(Form)
        self.select_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.select_box.setObjectName("select_box")
        self.horizontalLayout_3.addWidget(self.select_box)
        self.save_button = QtGui.QPushButton(Form)
        self.save_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_3.addWidget(self.save_button)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.delete_button = QtGui.QPushButton(Form)
        self.delete_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout_4.addWidget(self.delete_button)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.log_box = QtGui.QTextBrowser(Form)
        self.log_box.setObjectName("log_box")
        self.verticalLayout.addWidget(self.log_box)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.start_all_button = QtGui.QPushButton(Form)
        self.start_all_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.start_all_button.setObjectName("start_all_button")
        self.horizontalLayout_5.addWidget(self.start_all_button)
        self.start_button = QtGui.QPushButton(Form)
        self.start_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout_5.addWidget(self.start_button)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.proc_box = QtGui.QProgressBar(Form)
        self.proc_box.setProperty("value", 24)
        self.proc_box.setObjectName("proc_box")
        self.horizontalLayout_6.addWidget(self.proc_box)
        self.abort_button = QtGui.QPushButton(Form)
        self.abort_button.setEnabled(False)
        self.abort_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.abort_button.setObjectName("abort_button")
        self.horizontalLayout_6.addWidget(self.abort_button)
        self.verticalLayout.addLayout(self.horizontalLayout_6)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "SynTool", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "  源文件夹", None, QtGui.QApplication.UnicodeUTF8))
        self.source_button.setText(QtGui.QApplication.translate("Form", "浏览", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "目标文件夹", None, QtGui.QApplication.UnicodeUTF8))
        self.target_button.setText(QtGui.QApplication.translate("Form", "浏览", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "选择保存项", None, QtGui.QApplication.UnicodeUTF8))
        self.save_button.setText(QtGui.QApplication.translate("Form", "保存", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "  操作历史", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_button.setText(QtGui.QApplication.translate("Form", "删除", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "  准备就绪", None, QtGui.QApplication.UnicodeUTF8))
        self.start_all_button.setText(QtGui.QApplication.translate("Form", "开始全部", None, QtGui.QApplication.UnicodeUTF8))
        self.start_button.setText(QtGui.QApplication.translate("Form", "开始", None, QtGui.QApplication.UnicodeUTF8))
        self.abort_button.setText(QtGui.QApplication.translate("Form", "中断", None, QtGui.QApplication.UnicodeUTF8))

